CREATE TABLE IF NOT EXISTS tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number VARCHAR(50) NOT NULL,
    capacity INT NOT NULL CHECK (capacity > 0)
);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_code VARCHAR(50) NOT NULL UNIQUE,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    reservation_time TIMESTAMP NOT NULL,
    party_size INT NOT NULL CHECK (party_size > 0),
    status VARCHAR(20) NOT NULL,
    assigned_table_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservation_table FOREIGN KEY (assigned_table_id) REFERENCES tables(id),
    CONSTRAINT uq_reservation_table_slot UNIQUE (assigned_table_id, reservation_time)
);

CREATE INDEX IF NOT EXISTS idx_tables_capacity ON tables(capacity);
